# Imports et lecture donn√©es

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("Datagenus.csv", sep="\t", decimal=',')

In [ ]:
data

,code,gen1,gen2,gen3,gen4,gen5,gen6,gen7,gen8,gen9,...,evi_17,evi_18,evi_19,evi_20,evi_21,evi_22,evi_23,lon,lat,surface
0,1299,0,0,0,0,0,2,0,55,2,...,0.557684,0.498908,0.506745,0.489986,0.489789,0.489939,0.384010,16.005650,1.501416,5.0
1,2644,9,0,3,0,2,2,1,14,1,...,0.463382,0.455309,0.460387,0.453353,0.437797,0.439492,0.343511,17.017664,2.625876,15.0
2,1838,9,0,0,0,1,0,3,0,4,...,0.513755,0.497635,0.479529,0.498268,0.477358,0.448227,0.398150,16.455434,1.426452,17.5
3,534,0,4,0,0,9,1,11,19,0,...,0.492185,0.515405,0.474853,0.509785,0.446308,0.437621,0.401296,15.293492,3.862781,20.5
4,3213,1,1,0,0,0,0,4,5,1,...,0.513906,0.501724,0.498798,0.489223,0.451065,0.417405,0.379862,17.542412,2.775803,10.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3167,0,0,1,0,0,0,0,6,0,...,0.503707,0.513070,0.478461,0.471461,0.462705,0.412106,0.372042,17.467448,3.712853,5.0
996,2505,1,0,3,2,0,0,0,7,0,...,0.498634,0.479332,0.459527,0.406877,0.420388,0.396081,0.346393,16.905218,3.562925,5.5
997,1308,2,0,0,0,0,1,0,0,0,...,0.541860,0.498481,0.509058,0.516710,0.501647,0.496872,0.411050,16.043132,0.451920,3.5
998,1177,0,0,0,1,1,1,3,1,0,...,0.487574,0.487754,0.452440,0.432426,0.432392,0.425736,0.360591,15.855722,3.525443,7.0
999,358,2,0,0,2,0,3,1,0,0,...,0.483461,0.483084,0.458189,0.456983,0.435537,0.423099,0.363341,14.618817,3.712853,11.0

Calcul de Y (treedensity)

In [ ]:
treedensity = (
    data
    [[f"gen{i}" for i in range(1, 27 +1)]]
    .sum(axis="columns")
    /data["surface"]
)

In [ ]:
treedensity

0      35.000000
1       9.600000
2      11.085714
3      21.024390
4      11.809524
         ...
995    15.000000
996    20.545455
997     3.142857
998    21.571429
999     7.000000
Length: 1000, dtype: float64

Calcul des carr√©s des variables g√©ographiques quantitatives

In [ ]:
geography_quant = (
    data
     [
         ["lon", "lat", "altitude", "pluvio_yr"]
         + [f'pluvio_{i}' for i in range(1, 12 +1)]
     ]
)

In [ ]:
geography_quant

,lon,lat,altitude,pluvio_yr,pluvio_1,pluvio_2,pluvio_3,pluvio_4,pluvio_5,pluvio_6,pluvio_7,pluvio_8,pluvio_9,pluvio_10,pluvio_11,pluvio_12
0,16.005650,1.501416,398.622040,1455.000000,73.666664,74.500000,133.833328,139.333328,120.500000,110.333336,105.666664,105.833336,155.166672,169.833328,150.000000,92.166664
1,17.017664,2.625876,400.457642,1461.000000,50.666668,72.833336,118.500000,125.000000,132.500000,112.833336,134.166672,136.666672,157.000000,175.000000,99.833336,58.333332
2,16.455434,1.426452,362.229370,1447.000000,72.007019,77.605255,147.545609,144.017548,133.798248,104.957901,110.329826,104.836845,151.857880,158.308777,144.184219,86.184204
3,15.293492,3.862781,600.887634,1401.222168,22.534365,61.783485,118.256035,138.080811,154.522400,149.637466,154.465637,151.388351,169.922714,171.988037,83.422699,24.584211
4,17.542412,2.775803,375.827911,1403.333374,50.894459,77.603828,106.052017,123.153755,113.636513,127.284393,133.544296,147.499435,150.261139,164.740387,102.782280,43.306248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,17.467448,3.712853,518.807312,1410.444458,23.836740,49.291805,122.547791,108.115471,105.125137,150.381683,159.721268,178.480667,166.910126,179.923203,80.756538,31.121731
996,16.905218,3.562925,571.623962,1463.000000,35.128590,52.693321,131.538940,113.618042,127.598999,143.526657,154.409485,185.822784,171.431458,195.249557,93.742821,25.155243
997,16.043132,0.451920,355.232788,1429.222168,77.306496,108.427719,129.966644,162.902008,119.749550,86.263390,70.949860,74.317101,141.192429,175.164688,173.508591,98.964600
998,15.855722,3.525443,651.120422,1518.876587,24.089836,55.950462,137.265121,144.006699,140.983261,145.607849,156.472595,167.292679,186.003067,202.604843,111.035316,31.231792
999,14.618817,3.712853,673.363708,1470.000000,30.499969,57.833279,129.833389,150.500046,166.000076,144.666672,149.500015,135.500107,196.166687,183.000061,112.666565,22.833321

In [ ]:
geography_squares = (
  (geography_quant**2)
  .rename({
    col_name : f"squared_{col_name}"
    for col_name in geography_quant.columns
  }, axis="columns")
)

In [ ]:
geography_squares

,squared_lon,squared_lat,squared_altitude,squared_pluvio_yr,squared_pluvio_1,squared_pluvio_2,squared_pluvio_3,squared_pluvio_4,squared_pluvio_5,squared_pluvio_6,squared_pluvio_7,squared_pluvio_8,squared_pluvio_9,squared_pluvio_10,squared_pluvio_11,squared_pluvio_12
0,256.180839,2.254250,158899.530610,2.117025e+06,5426.777403,5550.250000,17911.359750,19413.776360,14520.250000,12173.445006,11165.443907,11200.694983,24076.696023,28843.359383,22500.000000,8494.693976
1,289.600882,6.895222,160366.322717,2.134521e+06,2567.111240,5304.694815,14042.250000,15625.000000,17556.250000,12731.361685,18000.695809,18677.779168,24649.000000,30625.000000,9966.694952,3402.777629
2,270.781309,2.034765,131210.116576,2.093809e+06,5185.010791,6022.575623,21769.706594,20741.054019,17901.971246,11016.160983,12172.670584,10990.764153,23060.815608,25061.668829,20789.089113,7427.717037
3,233.890913,14.921077,361065.949027,1.963424e+06,507.797592,3817.199070,13984.489779,19066.310241,23877.172072,22391.371360,23859.633078,22918.432952,28873.728812,29579.884909,6959.346704,604.383448
4,307.736205,7.705085,141246.618970,1.969345e+06,2590.245934,6022.354187,11247.030355,15166.847417,12913.257031,16201.316780,17834.079065,21756.083451,22578.409868,27139.395097,10564.197075,1875.431091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,305.111727,13.785278,269161.026997,1.989354e+06,568.190197,2429.682067,15017.960963,11688.955045,11051.294498,22614.650687,25510.883356,31855.348534,27858.990072,32372.358803,6521.618493,968.562128
996,285.786391,12.694436,326753.954393,2.140369e+06,1234.017809,2776.586102,17302.492849,12909.059466,16281.504552,20599.901300,23842.289016,34530.107211,29388.744627,38122.389702,8787.716440,632.786246
997,257.382091,0.204232,126190.333731,2.042676e+06,5976.294272,11756.570273,16891.328627,26537.064229,14339.954693,7441.372383,5033.882580,5523.031430,19935.301891,30682.667961,30105.231046,9793.991976
998,251.403929,12.428749,423957.804419,2.306986e+06,580.320204,3130.454236,18841.713569,20737.929244,19876.279913,21201.645726,24483.673053,27986.840391,34597.140940,41048.722464,12328.841503,975.424860
999,213.709803,13.785278,453418.683920,2.160900e+06,930.248138,3344.688120,16856.708973,22650.263779,27556.025330,20928.445916,22350.254562,18360.278946,38481.369093,33489.022339,12693.754856,521.360530

Indicatrices de la variable

In [ ]:
geology_categories = data["geology"].unique()
geology_ind = pd.DataFrame({
    f"geology_cat{cat}": (data["geology"] == cat).astype(float)
    for cat_id, cat in enumerate(geology_categories)
})

In [ ]:
geology_categories

array([3, 6, 5, 2, 1])

In [ ]:
geology_ind

     geology_cat3  geology_cat6  geology_cat5  geology_cat2  geology_cat1
0             1.0           0.0           0.0           0.0           0.0
1             0.0           1.0           0.0           0.0           0.0
2             0.0           1.0           0.0           0.0           0.0
3             0.0           0.0           1.0           0.0           0.0
4             0.0           1.0           0.0           0.0           0.0
..            ...           ...           ...           ...           ...
995           1.0           0.0           0.0           0.0           0.0
996           1.0           0.0           0.0           0.0           0.0
997           0.0           1.0           0.0           0.0           0.0
998           0.0           0.0           1.0           0.0           0.0
999           0.0           0.0           1.0           0.0           0.0

[1000 rows x 5 columns]

In [ ]:
features = (
    pd.concat(
        [
            geography_quant,
            geography_squares,
            geology_ind,
            data[[f"evi_{i}" for i in range(1, 23 +1)]]
        ],
        axis="columns"
    )
)

In [ ]:
features.columns

Index(['lon', 'lat', 'altitude', 'pluvio_yr', 'pluvio_1', 'pluvio_2',
       'pluvio_3', 'pluvio_4', 'pluvio_5', 'pluvio_6', 'pluvio_7', 'pluvio_8',
       'pluvio_9', 'pluvio_10', 'pluvio_11', 'pluvio_12', 'squared_lon',
       'squared_lat', 'squared_altitude', 'squared_pluvio_yr',
       'squared_pluvio_1', 'squared_pluvio_2', 'squared_pluvio_3',
       'squared_pluvio_4', 'squared_pluvio_5', 'squared_pluvio_6',
       'squared_pluvio_7', 'squared_pluvio_8', 'squared_pluvio_9',
       'squared_pluvio_10', 'squared_pluvio_11', 'squared_pluvio_12',
       'geology_cat3', 'geology_cat6', 'geology_cat5', 'geology_cat2',
       'geology_cat1', 'evi_1', 'evi_2', 'evi_3', 'evi_4', 'evi_5', 'evi_6',
       'evi_7', 'evi_8', 'evi_9', 'evi_10', 'evi_11', 'evi_12', 'evi_13',
       'evi_14', 'evi_15', 'evi_16', 'evi_17', 'evi_18', 'evi_19', 'evi_20',
       'evi_21', 'evi_22', 'evi_23'],
      dtype='object')

Correlation

In [ ]:
features.corr()

,lon,lat,altitude,pluvio_yr,pluvio_1,pluvio_2,pluvio_3,pluvio_4,pluvio_5,pluvio_6,...,evi_14,evi_15,evi_16,evi_17,evi_18,evi_19,evi_20,evi_21,evi_22,evi_23
lon,1.000000,0.054471,-0.621431,-0.219980,0.029697,-0.035571,-0.205745,-0.756158,-0.826475,0.157611,...,0.305150,0.424453,0.183469,0.022843,0.013861,0.177268,0.174974,0.123805,-0.008678,-0.085204
lat,0.054471,1.000000,0.631081,0.118869,-0.960454,-0.919003,-0.465361,-0.270048,0.282761,0.875890,...,0.055096,-0.132495,-0.102542,-0.246166,-0.351577,-0.403931,-0.516005,-0.628859,-0.622118,-0.509322
altitude,-0.621431,0.631081,1.000000,0.323496,-0.660276,-0.606495,-0.204916,0.295563,0.705330,0.526229,...,-0.143373,-0.385752,-0.192199,-0.143385,-0.245758,-0.407294,-0.502585,-0.499277,-0.377046,-0.218747
pluvio_yr,-0.219980,0.118869,0.323496,1.000000,-0.085421,-0.148982,0.279614,0.391675,0.388142,0.175567,...,-0.380751,-0.379034,-0.333712,-0.307485,-0.344593,-0.320737,-0.348081,-0.306400,-0.167698,-0.121975
pluvio_1,0.029697,-0.960454,-0.660276,-0.085421,1.000000,0.903370,0.410706,0.234842,-0.339605,-0.840180,...,-0.040396,0.154929,0.152648,0.250301,0.365007,0.429077,0.552972,0.633558,0.636144,0.494897
pluvio_2,-0.035571,-0.919003,-0.606495,-0.148982,0.903370,1.000000,0.422111,0.303407,-0.258633,-0.839939,...,-0.015552,0.187981,0.210132,0.221836,0.378858,0.402178,0.519626,0.640513,0.598859,0.464564
pluvio_3,-0.205745,-0.465361,-0.204916,0.279614,0.410706,0.422111,1.000000,0.428630,0.187316,-0.530749,...,-0.190068,-0.084032,-0.100782,-0.082775,0.017994,0.078848,0.109464,0.117876,0.122262,0.176410
pluvio_4,-0.756158,-0.270048,0.295563,0.391675,0.234842,0.303407,0.428630,1.000000,0.675115,-0.263805,...,-0.424014,-0.404210,-0.141913,-0.157279,0.039972,-0.025477,-0.043320,0.049020,0.222698,0.281018
pluvio_5,-0.826475,0.282761,0.705330,0.388142,-0.339605,-0.258633,0.187316,0.675115,1.000000,0.137919,...,-0.338272,-0.459426,-0.285206,-0.219989,-0.207721,-0.334916,-0.364751,-0.370391,-0.245538,-0.111532
pluvio_6,0.157611,0.875890,0.526229,0.175567,-0.840180,-0.839939,-0.530749,-0.263805,0.137919,1.000000,...,0.130010,-0.044897,-0.041600,-0.164872,-0.219824,-0.276884,-0.411002,-0.471860,-0.444833,-0.337784
pluvio_7,0.347394,0.852104,0.316472,0.110723,-0.819914,-0.801889,-0.345890,-0.495557,0.014941,0.744902,...,0.052443,-0.068997,-0.211415,-0.300648,-0.429555,-0.369850,-0.420950,-0.551075,-0.607595,-0.517442
pluvio_8,0.370115,0.885617,0.380348,0.103950,-0.864010,-0.860807,-0.479459,-0.564886,-0.033079,0.802744,...,0.117024,-0.018064,-0.136821,-0.208116,-0.375730,-0.391777,-0.497963,-0.581533,-0.645718,-0.535376
pluvio_9,-0.437474,0.725152,0.844762,0.435919,-0.749638,-0.697405,-0.253654,0.151025,0.621177,0.616095,...,-0.203989,-0.352133,-0.286521,-0.255644,-0.405029,-0.517576,-0.597639,-0.594139,-0.530084,-0.412663
pluvio_10,-0.602711,0.269091,0.706217,0.488064,-0.339373,-0.353257,-0.087138,0.319293,0.560570,0.230311,...,-0.188994,-0.346101,-0.193059,0.001774,-0.118401,-0.312954,-0.408638,-0.347775,-0.218734,-0.109623
pluvio_11,-0.380628,-0.887884,-0.328484,0.031054,0.844086,0.810985,0.472769,0.563440,0.012128,-0.740559,...,-0.177177,-0.023684,0.040881,0.198004,0.333419,0.347149,0.400891,0.542842,0.627750,0.565674
pluvio_12,-0.025149,-0.966044,-0.615971,-0.074746,0.952578,0.878302,0.480388,0.227856,-0.305628,-0.841685,...,0.013842,0.181230,0.144083,0.278938,0.350196,0.412805,0.540467,0.607608,0.586715,0.483523
squared_lon,0.998976,0.074361,-0.609646,-0.215147,0.014545,-0.052477,-0.221801,-0.746413,-0.818963,0.180853,...,0.292463,0.412604,0.178753,0.008557,0.007497,0.173921,0.166280,0.113987,-0.011169,-0.088232
squared_lat,0.013230,0.983502,0.663107,0.080804,-0.957500,-0.887710,-0.440157,-0.235318,0.306709,0.872499,...,0.114244,-0.085884,-0.031950,-0.192844,-0.281173,-0.367864,-0.491651,-0.583692,-0.579398,-0.440930
squared_altitude,-0.638966,0.613013,0.995504,0.335416,-0.641096,-0.583551,-0.182523,0.342089,0.725787,0.510204,...,-0.189199,-0.417276,-0.214716,-0.179351,-0.255080,-0.406035,-0.504708,-0.495809,-0.361767,-0.196873
squared_pluvio_yr,-0.223028,0.123987,0.328974,0.999833,-0.091311,-0.153363,0.277296,0.391348,0.392110,0.180200,...,-0.377035,-0.377328,-0.331254,-0.305129,-0.343098,-0.321709,-0.349110,-0.308776,-0.171347,-0.123920
squared_pluvio_1,-0.023470,-0.960727,-0.607011,-0.100820,0.986537,0.905556,0.423093,0.251272,-0.313811,-0.830271,...,0.027915,0.195003,0.210373,0.310528,0.421251,0.449875,0.571181,0.658381,0.653515,0.540330
squared_pluvio_2,-0.045932,-0.911251,-0.579991,-0.149709,0.882097,0.993292,0.420082,0.307959,-0.254702,-0.816604,...,-0.006593,0.185751,0.217797,0.230033,0.391763,0.397366,0.497655,0.638584,0.599952,0.479598
squared_pluvio_3,-0.183630,-0.469486,-0.226131,0.265144,0.412350,0.428482,0.998249,0.411431,0.169667,-0.530969,...,-0.186600,-0.074718,-0.105350,-0.087470,0.015420,0.085013,0.113954,0.124081,0.122091,0.176945
squared_pluvio_4,-0.771674,-0.238783,0.329462,0.387003,0.199227,0.265999,0.391614,0.996893,0.687550,-0.230584,...,-0.443795,-0.432304,-0.165967,-0.175338,0.021279,-0.045993,-0.073966,0.021437,0.202086,0.268168
squared_pluvio_5,-0.818023,0.304637,0.713228,0.393521,-0.355735,-0.278251,0.154540,0.672215,0.996220,0.167579,...,-0.354206,-0.474042,-0.292135,-0.241181,-0.220432,-0.342089,-0.374140,-0.377214,-0.245036,-0.113182
squared_pluvio_6,0.171233,0.857732,0.507310,0.171136,-0.823376,-0.823507,-0.527925,-0.269040,0.119577,0.997504,...,0.144258,-0.024439,-0.024943,-0.146471,-0.198324,-0.255770,-0.388449,-0.448174,-0.419656,-0.312377
squared_pluvio_7,0.360175,0.852545,0.324061,0.087841,-0.824825,-0.800589,-0.380846,-0.527138,-0.012883,0.767103,...,0.114646,-0.017093,-0.157189,-0.250050,-0.379890,-0.342236,-0.394585,-0.515837,-0.578461,-0.482137
squared_pluvio_8,0.377772,0.857970,0.378626,0.094543,-0.847475,-0.841418,-0.483785,-0.583809,-0.063642,0.797159,...,0.159236,0.012173,-0.101971,-0.163288,-0.333578,-0.369884,-0.486461,-0.551074,-0.618360,-0.500433
squared_pluvio_9,-0.453463,0.710255,0.846976,0.442097,-0.737864,-0.681813,-0.242647,0.172125,0.634177,0.603947,...,-0.214358,-0.358063,-0.287366,-0.258286,-0.401260,-0.510931,-0.590639,-0.583372,-0.510953,-0.394650
squared_pluvio_10,-0.600323,0.274184,0.707296,0.505732,-0.344086,-0.359065,-0.079788,0.336363,0.566167,0.243746,...,-0.203132,-0.358778,-0.202195,-0.013706,-0.123441,-0.313431,-0.416406,-0.355618,-0.219726,-0.106169
squared_pluvio_11,-0.368283,-0.886777,-0.324675,-0.009273,0.840260,0.815412,0.458963,0.540009,-0.012077,-0.735513,...,-0.125866,0.015346,0.090306,0.238820,0.370299,0.368388,0.416721,0.562844,0.638388,0.583449
squared_pluvio_12,-0.087400,-0.937248,-0.533916,-0.066320,0.922374,0.855008,0.470238,0.258866,-0.257173,-0.795500,...,0.056964,0.196876,0.180274,0.320493,0.386693,0.415420,0.529044,0.607765,0.589465,0.510591
geology_cat3,0.272609,0.227388,0.129542,-0.095799,-0.249235,-0.317017,-0.353250,-0.470921,-0.295441,0.316496,...,0.194241,0.143009,0.050984,0.191816,-0.014339,-0.064868,-0.153917,-0.141801,-0.142982,-0.077272
geology_cat6,0.311027,-0.468887,-0.615125,-0.155116,0.479448,0.510301,0.254700,-0.021576,-0.331003,-0.507990,...,-0.198624,0.013459,-0.123027,-0.198858,-0.024497,0.113967,0.195917,0.266544,0.175282,0.148405
geology_cat5,-0.690761,0.467585,0.715805,0.222600,-0.513280,-0.390596,-0.028873,0.506179,0.799606,0.361786,...,-0.152526,-0.319277,-0.146532,-0.203806,-0.164926,-0.271772,-0.322179,-0.321623,-0.243492,-0.095662
geology_cat2,0.322407,0.085099,-0.207568,-0.003315,-0.008490,-0.091081,0.045883,-0.102761,-0.174927,0.133642,...,0.096563,0.183669,0.156440,0.015456,0.061752,0.155521,0.156138,0.057237,0.091296,0.050764
geology_cat1,-0.233692,-0.286490,-0.011188,0.093638,0.302313,0.258693,0.128773,0.147602,0.040965,-0.257072,...,0.145082,0.041869,0.184887,0.279384,0.226561,0.152957,0.222831,0.171901,0.186436,-0.030563
evi_1,-0.313226,-0.228003,0.174890,0.011130,0.222009,0.176352,-0.185526,0.254863,0.080026,-0.088381,...,0.205464,0.197168,0.336443,0.429506,0.465723,0.407031,0.393240,0.511152,0.628669,0.662155
evi_2,-0.179470,-0.357766,0.010937,0.079170,0.342637,0.317410,-0.039961,0.181891,-0.015275,-0.255009,...,0.166151,0.183728,0.233092,0.387186,0.384253,0.376079,0.400820,0.524634,0.644079,0.670650
evi_3,-0.235647,-0.235841,0.136549,0.148555,0.243845,0.135008,-0.041577,0.237103,0.084805,-0.139495,...,0.091150,0.074145,0.181758,0.296722,0.293923,0.317928,0.290089,0.389861,0.553173,0.566495
evi_4,-0.092343,-0.420171,-0.127081,0.018357,0.434946,0.412324,0.057475,0.221106,-0.073372,-0.323277,...,0.142687,0.176847,0.302530,0.314641,0.420829,0.370391,0.423384,0.545475,0.617169,0.621345
evi_5,0.068923,-0.353323,-0.147499,0.061148,0.373473,0.301549,0.033773,0.017805,-0.201941,-0.226183,...,0.271255,0.279661,0.281724,0.355839,0.354298,0.390959,0.371807,0.509110,0.505997,0.551281
evi_6,-0.133894,-0.136253,0.077909,0.023746,0.110498,0.060487,-0.046327,-0.047085,-0.015018,-0.107636,...,0.297359,0.251506,0.201633,0.382598,0.260871,0.221622,0.248800,0.328374,0.304556,0.324719
evi_7,-0.269468,-0.123481,0.110483,-0.055224,0.157691,0.209683,-0.049762,0.255768,0.163139,-0.106903,...,0.416049,0.361524,0.555015,0.470976,0.519909,0.430365,0.484483,0.472289,0.509543,0.472096
evi_8,0.141461,-0.082858,-0.139747,-0.187526,0.128473,0.152845,-0.185264,-0.172362,-0.219490,-0.036789,...,0.641045,0.602314,0.671384,0.602896,0.578861,0.553583,0.605690,0.529626,0.481575,0.390428
evi_9,-0.176979,-0.114456,0.013407,-0.223216,0.099582,0.200110,0.007995,0.069193,0.056111,-0.121003,...,0.567235,0.496532,0.575129,0.519152,0.552593,0.515801,0.547163,0.501475,0.429714,0.432882
evi_10,0.107554,0.140501,-0.024441,-0.329381,-0.100923,-0.041128,-0.207078,-0.166451,-0.139014,0.177162,...,0.745498,0.660601,0.759938,0.605592,0.612814,0.518390,0.503154,0.411719,0.342608,0.286320
evi_11,-0.077818,0.125411,0.064200,-0.240683,-0.110487,-0.020151,-0.073880,-0.097973,0.069212,0.072794,...,0.683899,0.598855,0.661866,0.555543,0.521266,0.418770,0.443016,0.341297,0.212160,0.190152
evi_12,-0.037070,0.268571,0.161173,-0.217735,-0.256485,-0.131917,-0.091937,-0.117782,0.089682,0.217533,...,0.695105,0.547802,0.633662,0.488172,0.482434,0.365476,0.356353,0.239728,0.143082,0.173683
evi_13,0.131058,0.292382,0.124168,-0.261378,-0.289251,-0.203009,-0.185695,-0.331794,-0.077055,0.254180,...,0.756735,0.618658,0.640845,0.542681,0.388303,0.304170,0.303185,0.204464,0.089607,0.102343
evi_14,0.305150,0.055096,-0.143373,-0.380751,-0.040396,-0.015552,-0.190068,-0.424014,-0.338272,0.130010,...,1.000000,0.725504,0.711737,0.637787,0.561275,0.496804,0.507443,0.418062,0.281889,0.243910
evi_15,0.424453,-0.132495,-0.385752,-0.379034,0.154929,0.187981,-0.084032,-0.404210,-0.459426,-0.044897,...,0.725504,1.000000,0.676441,0.601969,0.594154,0.580742,0.596650,0.547676,0.387921,0.350036
evi_16,0.183469,-0.102542,-0.192199,-0.333712,0.152648,0.210132,-0.100782,-0.141913,-0.285206,-0.041600,...,0.711737,0.676441,1.000000,0.592120,0.669034,0.563413,0.591633,0.543836,0.479665,0.377889
evi_17,0.022843,-0.246166,-0.143385,-0.307485,0.250301,0.221836,-0.082775,-0.157279,-0.219989,-0.164872,...,0.637787,0.601969,0.592120,1.000000,0.625321,0.551177,0.559368,0.559140,0.464824,0.403259
evi_18,0.013861,-0.351577,-0.245758,-0.344593,0.365007,0.378858,0.017994,0.039972,-0.207721,-0.219824,...,0.561275,0.594154,0.669034,0.625321,1.000000,0.673668,0.669789,0.670529,0.606141,0.588948
evi_19,0.177268,-0.403931,-0.407294,-0.320737,0.429077,0.402178,0.078848,-0.025477,-0.334916,-0.276884,...,0.496804,0.580742,0.563413,0.551177,0.673668,1.000000,0.736762,0.684874,0.679481,0.637951
evi_20,0.174974,-0.516005,-0.502585,-0.348081,0.552972,0.519626,0.109464,-0.043320,-0.364751,-0.411002,...,0.507443,0.596650,0.591633,0.559368,0.669789,0.736762,1.000000,0.763430,0.699764,0.633267
evi_21,0.123805,-0.628859,-0.499277,-0.306400,0.633558,0.640513,0.117876,0.049020,-0.370391,-0.471860,...,0.418062,0.547676,0.543836,0.559140,0.670529,0.684874,0.763430,1.000000,0.812822,0.723533
evi_22,-0.008678,-0.622118,-0.377046,-0.167698,0.636144,0.598859,0.122262,0.222698,-0.245538,-0.444833,...,0.281889,0.387921,0.479665,0.464824,0.606141,0.679481,0.699764,0.812822,1.000000,0.801095
evi_23,-0.085204,-0.509322,-0.218747,-0.121975,0.494897,0.464564,0.176410,0.281018,-0.111532,-0.337784,...,0.243910,0.350036,0.377889,0.403259,0.588948,0.637951,0.633267,0.723533,0.801095,1.000000

Rang

In [ ]:
np.linalg.matrix_rank(features)

np.int64(60)

In [ ]:
features.shape

(1000, 60)

2. Premi√®re r√©gression sur composantes principales:

In [ ]:
import sklearn

In [ ]:
pca_features = sklearn.decomposition.PCA().fit_transform(features)
pca_features

array([[-5.98105983e+04,  4.62429758e+04, -1.01540314e+04, ...,
        -8.34549705e-03, -2.05427936e-02,  7.39765899e-09],
       [-4.81140369e+04,  5.92199185e+04,  5.56961710e+03, ...,
         5.63363656e-03, -5.69658945e-03, -5.80597570e-09],
       [-9.56989703e+04,  4.26077402e+04, -9.44595368e+03, ...,
         1.53234517e-02, -3.32062947e-03,  8.43659337e-09],
       ...,
       [-1.28960542e+05,  3.64122798e+03, -2.38017105e+04, ...,
        -6.73404606e-05, -9.78542578e-03,  3.97582380e-08],
       [ 2.67336176e+05,  5.34589363e+04,  5.36376214e+03, ...,
         7.51748833e-03, -6.07809789e-03, -5.18845300e-09],
       [ 2.09403905e+05, -8.37733578e+04, -5.04345177e+03, ...,
         1.05164084e-02, -3.53926351e-03, -1.81246322e-08]])

4. R√©gression PLS:

In [ ]:
X = features.to_numpy()
Y = treedensity.to_numpy()

In [ ]:
print(f"Dimensions de X : {X.shape}")
print(f"Dimensions de Y : {Y.shape}")

Dimensions de X : (1000, 60)
Dimensions de Y : (1000,)

In [ ]:
n_train = 900
n_folds = 9
fold_size = 100

In [ ]:
X_train = X[:n_train]
Y_train = Y[:n_train]

In [ ]:
result = {n_components: [] for n_components in range(2, 30 +1)}

for fold in range(n_folds):
  fold_start_index = fold*fold_size
  fold_end_index = (fold+1)*fold_size

  for n_components in range(2, 30 +1):
    pls_regression = sklearn.cross_decomposition.PLSRegression(n_components = n_components)

    X_fold_out = np.concatenate((X_train[:fold_start_index], X_train[fold_end_index:]))
    X_fold = X_train[fold_start_index:fold_end_index]

    Y_fold_out = np.concatenate((Y_train[:fold_start_index], Y_train[fold_end_index:]))
    Y_fold = Y_train[fold_start_index:fold_end_index]

    pls_regression.fit(X_fold_out, Y_fold_out)
    Y_hat_fold = pls_regression.predict(X_fold)

    metric = sklearn.metrics.mean_squared_error(Y_fold, Y_hat_fold)
    result[n_components].append(metric)

result_per_n_components = {
    n_components: sum(result[n_components])/n_folds
    for n_components in range(2, 30 +1)
}
result_per_n_components

{2: 53.64511554200064,
 3: 52.34848025161215,
 4: 51.783144980918756,
 5: 51.28160090817179,
 6: 50.946070062570236,
 7: 51.28923251411513,
 8: 51.54504851691737,
 9: 51.43870807614556,
 10: 51.185065361331745,
 11: 51.16803432608034,
 12: 51.34936523191922,
 13: 51.299155727352996,
 14: 51.25290922703377,
 15: 51.292343268616435,
 16: 51.19881269739107,
 17: 51.13323944257446,
 18: 51.07767289419288,
 19: 50.7676952548508,
 20: 50.951063423470686,
 21: 50.607368686621534,
 22: 50.65015643825208,
 23: 50.576120229098194,
 24: 50.66733201521541,
 25: 50.89214267344938,
 26: 51.35776178989007,
 27: 51.273357151634166,
 28: 51.150172110764174,
 29: 51.11516004711743,
 30: 51.03110522878787}

In [ ]:
n_components_optimal = list(result_per_n_components.keys())[np.argmin(list(result_per_n_components.values()))]

In [ ]:
n_components_optimal

23

In [ ]:
X_test = X[n_train:]
Y_test = Y[n_train:]

In [ ]:
pls_regression = sklearn.cross_decomposition.PLSRegression(n_components = n_components_optimal)
pls_regression.fit(X_train, Y_train)
Y_hat_test = pls_regression.predict(X_test)
sklearn.metrics.mean_squared_error(Y_test, Y_hat_test)

47.10048703442447